version: '3.9'
services:
  apidiabeteassessment:
    container_name: apidiabeteassessment
    build: .
    ports:
      - "21004:8083"
    environment:
      API_PATIENT_URL: "http://apipatient:8081"
      API_NOTE_URL: "http://apinotepatient:8082"
  mysql:
    container_name: patient
    build: ../Mediscreen/database
    ports:
      - "21003:3306"
  apipatient:
    container_name: apipatient
    build: ../Mediscreen/.
    ports:
      - "21002:8081"
    depends_on:
      - mysql
    environment:
      spring.datasource.url: "jdbc:mysql://mysql:3306/patient?serverTimezone=UTC"
  mongodb:
    container_name: mongodb
    build: ../mediscreenapinotes/database
    ports:
      - "21001:27017"
  apinotepatient:
    container_name: apinotepatient
    build: ../mediscreenapinotes/.
    ports:
      - "21000:8082"
    depends_on:
      - mongodb
    environment:
      spring.data.mongodb.uri: "mongodb://mongodb:27017/Notes"