version: '3.9'
services:
  mysql:
    container_name: mysql
    build: ../Mediscreen/database
    ports:
      - "21001:3306"
    environment:
      spring.datasource.url: "jdbc:mysql://mysql:3306/patient?serverTimezone=UTC"
      spring.datasource.username: "root"
      spring.datasource.password: "N4NTERRE2022!"
    networks:
      - mynetwork

  apipatient:
    container_name: apipatient
    build: ../Mediscreen/.
    ports:
      - "21000:8081"
    depends_on:
      - mysql
    environment:
      spring.datasource.url: "jdbc:mysql://mysql:3306/patient?serverTimezone=UTC"
      spring.datasource.username: "root"
      spring.datasource.password: "N4NTERRE2022!"
    networks:
      - mynetwork

  mongodb:
    container_name: mongodb
    build: ../mediscreenapinotes/database
    ports:
      - "21003:27017"
    networks:
      - mynetwork
  apinotepatient:
    container_name: apinotepatient
    build: ../mediscreenapinotes/.
    ports:
      - "21002:8082"
    depends_on:
      - mongodb
    environment:
      spring.data.mongodb.uri: "mongodb://mongodb:27017/Notes"
    networks:
      - mynetwork
  apidiabeteassessment:
    container_name: apidiabeteassessment
    build: .
    ports:
      - "22000:8083"
    depends_on:
      - apipatient
      - apinotepatient
    environment:
      API_PATIENT_URL: "Mediscreen:8081"
      API_NOTE_URL: "apinotepatient:8082"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
